version: '3.4'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./src:/app/src  # Mount the source code directory into the container
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
